### ISSUE TITLE
Equations are unreadable in dark mode

### ISSUE THREAD

**Issue by sbrl** [Mayuyu/suggested-notation-for-machine-learning#7]
If I have GitHub's dark mode enabled, all the equations in the README are completely unreadable due to a lack of contrast between the background and the equation text.

**Comment by mazhengcn** [comment]
> If I have GitHub's dark mode enabled, all the equations in the README are completely unreadable due to a lack of contrast between the background and the equation text.

Are you still having this issue? This seems due to the GitHub markdown theme but should be fixed now.

Here is what it looks like in my Safari with Github Dark Default theme.

<img width="876" alt="WX20220819-184539@2x" src="https://user-images.githubusercontent.com/5706194/185603090-75fe1db3-3125-407c-abee-9d795682564c.png">
